[project]
name = "novillex-ca-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "ipykernel>=6.29.5",
    "pandas>=2.2.3",
    "pdfplumber>=0.11.6",
    "uvicorn>=0.34.2",
]
